language: php

php:
- 7.1

sudo: false

branches:
  only:
  - master

before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev

install: composer install --no-interaction --prefer-source

script: phpunit